DROP TABLE ADOPTER IF EXISTS;
DROP TABLE ANIMAL IF EXISTS;

CREATE MEMORY TABLE ADOPTER(
      id integer primary key auto_increment NOT NULL,
      NAME VARCHAR(255) NOT NULL,
      PHONE_NUMBER INTEGER
);

CREATE MEMORY TABLE ANIMAL(
    id integer primary key auto_increment NOT NULL,
    NAME VARCHAR(255),
    TYPE VARCHAR(255),
    BREED VARCHAR(255),
    ADOPTER_ID INTEGER
);

ALTER TABLE ANIMAL ADD CONSTRAINT PUBLIC.Adopter_ID FOREIGN KEY(ADOPTER_ID) REFERENCES ADOPTER(ID) NOCHECK;
